/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/ pescaderia /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE pescaderia;

DROP TABLE IF EXISTS usuarios;
CREATE TABLE `usuarios` (
  `usuario` varchar(8) DEFAULT NULL,
  `contraseña` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;